const actionTypes = {
  GET_COLLECTIONS_START: 'GET_COLLECTIONS_START',
  GET_COLLECTIONS_SUCCESS: 'GET_COLLECTIONS_SUCCESS',
  GET_COLLECTION_BY_BRAND_NAME_START: 'GET_COLLECTION_BY_BRAND_NAME_START',
  GET_COLLECTION_BY_BRAND_NAME_SUCCESS: 'GET_COLLECTION_BY_BRAND_NAME_SUCCESS',
  GET_ITEM_START: 'GET_ITEM_START',
  GET_ITEM_SUCCESS: 'GET_ITEM_SUCCESS',
  QUERY_FAILURE: 'QUERY_FAILURE',
  SHOP_ERROR_CLEAN_UP: 'SHOP_ERROR_CLEAN_UP'
}

export default actionTypes;