const actionTypes = {
  ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
  REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
  REMOVE_ITEM_COMPLETELY_FROM_CART: 'REMOVE_ITEM_COMPLETELY_FROM_CART',
  TOGGLE_CART_DROPDOWN: 'TOGGLE_CART_DROPDOWN',
  CLEAR_CART: 'CLEAR_CART'
}

export default actionTypes;