const actionTypes = {
  GET_COMMENTS_START: 'GET_COMMENTS_START',
  GET_COMMENTS_SUCCESS: 'GET_COMMENTS_SUCCESS',
  GET_COMMENTS_FAILURE: 'GET_COMMENTS_FAILURE',
  ADD_COMMENT_START: 'ADD_COMMENT_START',
  ADD_COMMENT_SUCCESS: 'ADD_COMMENT_SUCCESS',
  ADD_COMMENT_FAILURE: 'ADD_COMMENT_FAILURE',
  REMOVE_COMMENTS_ON_UNMOUNT: 'REMOVE_COMMENTS_ON_UNMOUNT'
};

export default actionTypes;